Add snapshot deletion to cluster cleanup
stackhpc/cluster-api-janitor-openstack pull request #21
Opened 2023-11-24 11:06 UTC by sd109

2023-11-24 11:49 UTC, mkjpryor requested changes
Looks good. Just a couple of minor things.

2023-11-24 11:49 UTC, mkjpryor commented on capi_janitor/openstack/operator.py
> +                    await snapshots.delete(snapshot.id)
Do we also need the 400 protection here for the chained case that you mentioned?

2023-11-24 11:49 UTC, mkjpryor commented on capi_janitor/openstack/operator.py
> +            raise ResourcesStillPresentError("snapshots", name)
Can we use a separate `check_snapshots` here please? This avoids rechecking the snapshots in the case where backup is not enabled.

2023-11-24 13:57 UTC, sd109 commented on capi_janitor/openstack/operator.py
> +                    await snapshots.delete(snapshot.id)
Yes, probably safer to add it.

2023-11-26 21:49 UTC, mkjpryor approved these changes
LGTM

2023-11-26 21:50 UTC, merged